spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: postgres
    password: ${DB_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  
  mail:
    host: smtp.gmail.com
    port: 587
    default-encoding: utf-8
    username: ${MAIL_URL}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
  profiles:
    active: ${PROFILE}

server:
  port: 8080
  error:
    include-message: always

JWT-SECRET: ${JWT_SECRET}
